apiVersion: v1
kind: Service
metadata:
  name: log-request-headers
  labels:
    app: log-request-headers
spec:
  selector:
    app: log-request-headers
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
